#cloud-config

apt:
    sources:
        docker.list:
            source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
            keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 

groups:
    - docker

users:
    - name: user
      passwd: app
      groups:
          - docker
      lock_passwd: true

# install docker
packages:
    - docker-ce
    - docker-ce-cli
    - docker-compose

# add hostname
preserve_hostname: false
fqdn: edgybuntu.io
hostname: edgybuntu

ssh_pwauth: yes

write_files:
    - path: /etc/docker/daemon.json
      content: |
          {
             "log-driver": "json-file",
             "log-opts": {
              "max-size": "10m",
              "max-file": "3"
              }
          }

chpasswd:
    list:
        - user:app
